### ISSUE TITLE
NanoUI --> TGUI Conversion List

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#13728]
The following is a list of all UIs that need to be converted from NanoUI to TGUI

# Example PR for converting UIs from NanoUI to TGUI: #13732 

# Easy
*These UIs feature one page and should be relatively easy to convert, and are a good starting project*
**NONE**

# Medium
*These UIs feature multiple pages, feature large amounts of controls, or have complicated controls such as NanoMaps. These are a little more difficult*
**NONE**

# Hard
*These UIs are incredibly complex and have custom styling and other snowflake code. Attempt at your own risk*
**NONE**

# Reserved
*Thse UIs have been reserved by other people as part of a larger refactor. If you wish to reserve a UI, please ping me on Discord*
**NONE**

# Completed TGUIs
*This is a list of completed TGUIs to keep them out of the way of the todo list*
- [x] Accounts access terminal (accounts_terminal.tmpl) - Reserved by @AffectedArc07 [WIP] [#14697] 
- [x] AI Door control (door_control.tmpl) [#13935]
- [x] AI law manager (law_manager.tmpl) - Reserved by @AffectedArc07 [Working on it] [#14636] 
- [x] AI system integrity restorer (ai_fixer.tmpl) [#13944]
- [x] Air alarms (air_alarm.tmpl) - Reserved by @AffectedArc07 [Working on them] [#14620]
- [x] Airlock controller (advanced_airlock_console.tmpl) [#14604] 
- [x] APC (apc.tmpl) [#13888]
- [x] ATMs (atm.tmpl) - Reserved by @variableundefined [Requested] [#14799]
- [x] Autolathe (autolathe.tmpl) [#14225]
- [x] Body scanner (adv_medical.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] BSA (bsa.tmpl) [#13771]
- [x] Canisters (canister.tmpl) [#14001]
- [x] Cell management console (brig_cells.tmpl) [#14475] 
- [x] Cell timers (brig_timer.tmpl) [#14151]
- [x] Central atmospherics computer (atmos_control.tmpl, atmos_control_map_content.tmpl, atmos_control_map_header.tmpl) - Reserved by @AffectedArc07 [Working on them] [#14620] 
- [x] Chemical heater (chem_heater.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] Chemical dispenser (chem_dispenser.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] Chem master (chem_master.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] Cloning console (cloning_console.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] Communications console (comm_console.tmpl) [#14166]
- [x] Crafting menu (personal_crafting.tmpl) [#14700] 
- [x] Cyborg control console (robot_control.tmpl) [#14089]
- [x] DNA modifier (dna_modifier.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] DNA Vault (dna_vault.tmpl) - Reserved by @farie82 [Requested] [#14649] 
- [x] Door access console (door_access_console.tmpl) [#14608]
- [x] Doppler array (doppler_array.tmpl) - Reserved by @farie82 [Requested] [#14686] 
- [x] EFTPos scanner (eftpos.tmpl) - Reserved by @AffectedArc07 [WIP] [#14683]
- [x] Electropack (radio_electro.tmpl) [#14052]
- [x] ERT Config (ert_config.tmpl) [#14190] 
- [x] Exosuit control console (exosuit_control.tmpl) [#14427] 
- [x] Fax machines (faxmachine.tmpl) [#14078]
- [x] Gas filter (atmos_filter.tmpl) [#14320]
- [x] Gas mixer (atmos_mixer.tmpl) [#14333]
- [x] Gas pump, Volume pump, Passive gate (atmos_pump.tmpl) [#14308]
- [x] Generators (pacman.tmpl) [#14378]
- [x] Ghost role selection UI (spawners_menu.tmpl) [#14101]
- [x] Handheld air tanks (tanks.tmpl) [#14022]
- [x] Heaters & Freezers (freezer.tmpl) [#14241]
- [x] Identification console (identification_computer.tmpl) - Reserved by @Kyep [Waiting on #14011 for AccessList.js] [#14291]
- [x] Intellicard (aicard.tmpl) [#13961]
- [x] Keycard authentication device (keycard_auth.tmpl) [#14176]
- [x] Labor camp claim console (labor_claim_console.tmpl) [#14650] 
- [x] Mech bay recharger console (mech_bay_console.tmpl) [#14074]
- [x] Medical records (med_data.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] Medical cryotube (cryo.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] Mirrors + Change mob appearance (appearance_changer.tmpl) [#14648] 
- [x] Musical instruments (song.tmpl) [#13865]
- [x] Newscaster (newscaster.tmpl) - Reserved by @dearmochi [Already working on it] [#14527]
- [x] Nuke (nuclear_bomb.tmpl) [#14200]
- [x] Operating console (op_computer.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] pAIs (pai_atmosphere.tmpl, pai_bioscan.tmpl, pai_chatroom.tmpl, pai_directives.tmpl, pai_doorjack.tmpl, pai_interface.tmpl, pai_manifest.tmpl, pai_medrecords.tmpl, pai_messenger.tmpl, pai_radio.tmpl, pai_secrecords.tmpl, pai_signaller.tmpl) - Reserved by @AffectedArc07 [Already working on it] [#14524]
- [x] PDAs (pda.tmpl, pda_atmos_scan.tmpl, pda_janitor.tmpl, pda_main_menu.tmpl, pda_manifest.tmpl, pda_medical.tmpl, pda_messenger.tmpl, pda_mob_hunt.tmpl, pda_mule.tmpl, pda_notekeeper.tmpl, pda_power.tmpl, pda_secbot.tmpl, pda_security.tmpl, pda_signaller.tmpl, pda_status_display.tmpl, pda_supply) - Reserved by @AffectedArc07 [Has plans to do an entire PDA refactor] [#14403]
- [x] Pod tracking console (pod_tracking.tmpl) [#14639]
- [x] Pool controller (poolcontroller.tmpl) [#14476]
- [x] Portable air pump (portpump.tmpl) [#14371]
- [x] Portable air scrubber (portscrubber.tmpl) [#14385]
- [x] Power monitoring console (power_monitor.tmpl) - Reserved by @AffectedArc07 [Part of the PDA PR. Do not question it.] [#14403] 
- [x] R&D console (r_n_d.tmpl) - Reserved by @nicetoolbox [Already working on it] [#14484]
- [x] Radios (radio_basic.tmpl) [#14052]
- [x] RCD (rcd.tmpl) - Reserved by @SteelSlayer [Already working on it] [#14598] 
- [x] Request consoles (request_console.tmpl) - Reserved by @AffectedArc07 [WIP] [#14734]
- [x] RPD (rpd.tmpl) [#14702] 
- [x] Safe (safe.tmpl) [#14732]  
- [x] Security camera console (sec_camera.tmpl, sec_camera_map_content.tmpl, sec_camera_map_header.tmpl) - Reserved by @AffectedArc07 [Needs to use BYOND UI element for camera-in-window] [#13750]
- [x] Security records (secure_data.tmpl) - Reserved by @dearmochi [Already doing it] [#14422] 
- [x] Shield satellite control (sat_control.tmpl) [#14678]
- [x] Shuttle consoles (shuttle_console.tmpl) [#14065]
- [x] Shuttle manipulator (shuttle_manipulator.tmpl) [#14674]
- [x] Sleepers (sleeper.tmpl) - Reserved by @dearmochi [Wants to do all medical TGUIs at once] [#13738]
- [x] Slot machines (slotmachine.tmpl) [#13732]
- [x] Solar control console (solar_control.tmpl) [#14258]
- [x] Smartfridge (smartfridge.tmpl) [#14328]
- [x] SMES (smes.tmpl) [#14058]
- [x] Station alert consoles (alarm_monitor.tmpl, atmos_alert.tmpl, computer_main.tmpl) - Reserved by @Fox-McCloud [Alarm refactor] [#13751]
- [x] Supply console (order_shuttle.tmpl, supply_console.tmpl) - Reserved by @AffectedArc07 [Needs refactoring to use tgui_static_data()] [#14386]
- [x] Syndicate uplinks (uplink.tmpl) - Reserved by @AffectedArc07 [Doing as part of PDAs] [#14403]
- [x] Tank dispensers (tank_dispenser.tmpl) [#14388]
- [x] Tank transfer valve (transfer_valve.tmpl) [#14059]
- [x] Telecommunications core (tcomms_core.tmpl) - Reserved by @AffectedArc07 [Has plans to do them in a very specific way] [#14397]
- [x] Telecommunications relay (tcomms_relay.tmpl) - Reserved by @AffectedArc07 [Has plans to do them in a very specific way] [#14397] 
- [x] Teleporter console (teleporter_console.tmpl) [#14277] 
- [x] Turret control (turret_control.tmpl) [#14011]
- [x] Vending machines (vending_machine.tmpl) [#14075]
- [x] Wires (wires.tmpl) - Reserved by @SteelSlayer [Working on wires already] [#13769]

# TGUI Contributors
*List of all people who have contributed TGUIs. If you are not in this list, please ping me and ask*
- @AffectedArc07 
- @dearmochi 
- @Edan52 
- @farie82 
- @Fox-McCloud 
- @Kyep 
- @nicetoolbox 
- @RedWolfie 
- @Shadow-Quill 
- @SteelSlayer 
- @TDSSS 
- @variableundefined
